### ISSUE TITLE
Backtick is not being processed

### ISSUE THREAD

**Issue by Abr1k0sHelm** [mindedsecurity/JStillery#12]
Try this one:
```
a = String.fromCharCode`41`;
b = a
```
Expected result:
```
a = ')';
b = ')';
```
Сurrent result:
```
a = String.fromCharCode`41`;
b = String.fromCharCode`41`;
```

**Comment by Abr1k0sHelm** [comment]
More interesting example for this one:
```
setTimeout`\x61\x6c\x65\x72\x74\x28\x31\x29`
```
Expected result:
```
setTimeout('alert(1)');
```
Сurrent result:
```
setTimeout`\x61\x6c\x65\x72\x74\x28\x31\x29`;
```

**Comment by wisec** [comment]
Fixed

**Comment by wisec** [comment]
The result is going to be a little different than requested because a TaggedTemplateExpression could expect the argument as Template Literal, so we're not going to cast it to native string.
Anyway, the content is "reduced" as much as possible. 
```
e = 'e';
l = 'l';
setTimeout`\x61${l+e}rt`;
```
Result:
```
e = 'e';
l = 'l';
setTimeout`a${ 'le' }rt`;
