### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by hundan2020** [mindedsecurity/JStillery#13]
i don't know if it is my problem...because it worked for you...but i do face the problem.
i was started in powershell.
### error
**command:**
>echo 'a= String.fromCharCode(41);b=a'|  node ./jstillery_cli.js

**response:**
![1](https://user-images.githubusercontent.com/9510938/35624083-e0f28886-06c8-11e8-9b20-4fcc5d291984.png)

**command:*
>npm start

**response:**
![2](https://user-images.githubusercontent.com/9510938/35624158-20608478-06c9-11e8-8f27-dcb3584b9f3c.png)

**command:*
>node ./jstillery_cli.js

**response:**
![3](https://user-images.githubusercontent.com/9510938/35624224-51c04ed6-06c9-11e8-804a-b5d6ede6b53e.png)

### my environment
> node version:  v6.11.2
npm version: 3.10.10
OS: windows 10 1709 x64

**Comment by wisec** [comment]
the ** operator works on node > 6
You'll need node >= 7 
Sorry about that.

**Comment by hundan2020** [comment]
thank you
