### ISSUE TITLE
Eval issues

### ISSUE THREAD

**Issue by DayDun** [mindedsecurity/JStillery#28]
Eval places an unnecessary semicolon leading to a syntax error:
```js
([] + eval("5 + 5"))[0]
```
```js
([] + 10;)[0];
```

Other unexpected behavior:
```js
eval("5") + "test";
eval("") + "test";
```
```js
'undefinedtest';
({
}); + 'test';
```

It would also be great if more complex forms of function construction were supported, like:
```js
[].filter.constructor("return 5 + 5")();
Array.prototype.filter.constructor("return 5 + 5")();
Array.prototype.constructor.constructor("return 5 + 5")();
```

**Comment by wisec** [comment]
Hey @DayDun 
thanks for reporting this!
Fixed the eval issue!

About the *constructors* request, I'll consider to add an option for resolving them as opt-in.

Thanks!
