### ISSUE TITLE
Assignment is deobfuscated to undefined

### ISSUE THREAD

**Issue by samczsun** [mindedsecurity/JStillery#3]
JSFuck'd `x = 5`, deobfuscated result is

```
[].filter.constructor('x undefined 5')();
```

**Comment by wisec** [comment]
Thanks!

**Comment by wisec** [comment]
fixed! 
https://github.com/mindedsecurity/JStillery/commit/a3175a07cc29792763a94e8483721a3389ff7aee#diff-f2bff50c5b25d85d97f783590945ef8c
